# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "story-test"
client_id = "d0cad8a22457dd4218b4ab1b427eae0c"
application_url = "https://storytest-eb1803368b1d.herokuapp.com/"
embedded = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "unauthenticated_read_content,unauthenticated_read_customer_tags,unauthenticated_read_product_tags,unauthenticated_read_product_inventory,unauthenticated_read_product_listings,unauthenticated_write_checkouts,unauthenticated_read_checkouts,unauthenticated_write_customers,unauthenticated_read_customers,read_product_listings,read_inventory,read_products,write_script_tags,write_orders,read_price_rules"

[auth]
redirect_urls = [ "https://storytest-eb1803368b1d.herokuapp.com/" ]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "story-testing1.myshopify.com"
