/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7e1a2e15-db17-4380-b87b-433a04915356",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_nWx6jzKiM",
    "aws_user_pools_web_client_id": "1j4e8sul3f03sokt07qed5b1ib",
    "oauth": {}
};


export default awsmobile;
