export default Object.freeze({
    REACT_APP_QR_API_KEY: "VrxxJ8251IiRvf_YLHEZFB4-zoSpUTZsmEcGM4FkdVBeBq-RNuqlAOjeaXR0TRMM",
    CATALOGUE_API: "https://admin-qa-catalogue.borderfree.live",
    ADMIN_API: "https://tjckybvy59.execute-api.us-east-1.amazonaws.com/qa",
    CONSUMER_API: "https://ty6fllkl4d.execute-api.us-east-1.amazonaws.com/dev",
    WEBSOCKET_API: "wss://8y5806yto9.execute-api.us-east-1.amazonaws.com/dev",
    STREAM_CHAT_API_KEY: "8mhkpzwpeqva",
    STREEM_ID: "86324",
    FACEBOOK_APP_ID: 3517625721633002,
    FACEBOOK_API_URL: "https://graph.facebook.com",
    FACEBOOK_SDK_URL: "https://connect.facebook.net/en_US/sdk.js",
    GOOGLE_API_URL: "https://apis.google.com/js/api.js",
    GOOGLE_API_KEY: "AIzaSyBbe4MeRoftn3Pb37rllAEJDReL5Mhf7ps",
    GOOGLE_CLIENT_ID: "177699801520-s4503ebdb7ljc99oh2tiitsisodnum8m.apps.googleusercontent.com",
    GOOGLE_API_SCOPE: "https://www.googleapis.com/auth/youtube.force-ssl",
    GOOGLE_DISCOVERY_DOCS: "https://www.googleapis.com/discovery/v1/apis/youtube/v3/rest",
    ORGNAME: "streamstyle",
    DomainName: "https://zepter-consumer.borderfree.live",
    ORG_EMAIL: "support@tocara.live",
    DOLBY_URL: "https://session.voxeet.com/v1/api",
    DOLBY_USERID: "Spm9LGtN4ZW_eu-hHYJWTA==",
    DOLBY_PASSWD: "TaGYTSUPexia_pJaKiyBPibgksaTAiBYUgUWo7jzRbQ=",
    GO_LIVE_RETRIES: 20,
    RETRY_TIME: 6000,
    MAX_TIMEOUT: "10 minutes",
    UPLOAD_BUCKET_URL: "https://d241ihec4k611f.cloudfront.net",
    ANALYTICS_API_REFRESH: 300000,
    SPLIT_TOKEN: "__##__",
    SALES_TARGET_TIMER: 15000,
    REACT_APP_SHOPIFY_APP_ID: "d0cad8a22457dd4218b4ab1b427eae0c",
    ADMIN_URL: "https://zepter-admin.borderfree.live",
    REVO_URL: "https://www.revovideo.com",
    VALID_BROWSERS: {
        windows: {
            chrome: ">=81",
            firefox: ">=76",
            edge: ">=79",
        },
        linux: {
            firefox: ">=76",
            chrome: ">=81",
        },
        macos: {
            chrome: ">=81",
            firefox: ">=76",
            safari: ">=13",
        },
        android: {
            chrome: ">=81",
        },
        ios: {
            safari: ">=13",
        },
    },
});
