/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: "us-east-1",
    aws_cognito_identity_pool_id: "us-east-1:9a43ec58-3392-4053-8f4c-909e3c7aa133",
    aws_cognito_region: "us-east-1",
    aws_user_pools_id: "us-east-1_6GsRYzX0A",
    aws_user_pools_web_client_id: "1f7v42t12u58q7d0ame41se4p3",
    oauth: {},
};

export default awsmobile;