export default Object.freeze({
    REACT_APP_QR_API_KEY: "VrxxJ8251IiRvf_YLHEZFB4-zoSpUTZsmEcGM4FkdVBeBq-RNuqlAOjeaXR0TRMM",
    ADMIN_API: "https://u2465fkm22.execute-api.us-east-1.amazonaws.com/p",
    CONSUMER_API: "https://8qyo9gvzcc.execute-api.us-east-1.amazonaws.com/p",
    WEBSOCKET_API: "wss://k6g3lu835l.execute-api.us-east-1.amazonaws.com/p",
    STREAM_CHAT_API_KEY: "8mhkpzwpeqva",
    STREEM_ID: "86324",
    FACEBOOK_APP_ID: 3517625721633002,
    FACEBOOK_API_URL: "https://graph.facebook.com",
    FACEBOOK_SDK_URL: "https://connect.facebook.net/en_US/sdk.js",
    GOOGLE_API_URL: "https://apis.google.com/js/api.js",
    GOOGLE_API_KEY: "AIzaSyBbe4MeRoftn3Pb37rllAEJDReL5Mhf7ps",
    GOOGLE_CLIENT_ID: "177699801520-s4503ebdb7ljc99oh2tiitsisodnum8m.apps.googleusercontent.com",
    GOOGLE_API_SCOPE: "https://www.googleapis.com/auth/youtube.force-ssl",
    GOOGLE_DISCOVERY_DOCS: "https://www.googleapis.com/discovery/v1/apis/youtube/v3/rest",
    ORGNAME: "zepter",
    DomainName: "https://zepter.streamstyle.live",
    ORG_EMAIL: "support@streamstyle.live",
    DOLBY_URL: "https://session.voxeet.com/v1/api",
    DOLBY_USERID: "Spm9LGtN4ZW_eu-hHYJWTA==",
    DOLBY_PASSWD: "TaGYTSUPexia_pJaKiyBPibgksaTAiBYUgUWo7jzRbQ=",
    GO_LIVE_RETRIES: 20,
    RETRY_TIME: 6000,
    MAX_TIMEOUT: "10 minutes",
    UPLOAD_BUCKET_URL: "https://dwdg4h09xyedo.cloudfront.net",
    ANALYTICS_API_REFRESH: 300000,
    SALES_TARGET_TIMER: 15000,
    REACT_APP_SHOPIFY_APP_ID: "d0cad8a22457dd4218b4ab1b427eae0c",
});
